name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'New version type [major | minor | patch]'
        required: true
        default: 'patch'
jobs:
  bumpVersion:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "New version type: ${{ github.event.inputs.type }}"

      - name: Setup checkout
        uses: actions/checkout@v4
        with:
          # Use a PAT to ensure that
          #   commits are authored with a specific user
          #   workflow run are triggered after git push
          token: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: Config git
        run: |
          git config --local user.email "62586190+process-analytics-bot@users.noreply.github.com"
          git config --local user.name "process-analytics-bot"
          git config pull.rebase true

      - name: Checkout main
        run: git checkout main && git pull --tags

      - name: Generate new version
        id: release_version
        uses: zwaldowski/semver-release-action@v4
        with:
          dry_run: true
          bump: ${{ inputs.type }}
          prefix: v
          github_token: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: Update with the release version
        run: |
          CURRENT_VERSION=$(grep Version DESCRIPTION | sed 's/Version: \(.*\).9000/\1/g')
          sed -i -E "s/$CURRENT_VERSION/${{ steps.release_version.outputs.version }}/g" index.md
          sed -i -E "s/$CURRENT_VERSION/${{ steps.release_version.outputs.version }}/g" README.md
          sed -i -E "s/$CURRENT_VERSION.9000/${{ steps.release_version.outputs.version }}/g" cran-comments.md
          sed -i -E 's/Version: .*/Version: ${{ steps.release_version.outputs.version }}/g' DESCRIPTION

      - name: Commit with the release version
        run: |
          git add index.md
          git add README.md
          git add cran-comments.md
          git add DESCRIPTION
          git commit -m "chore(release): set the release version to ${{ steps.release_version.outputs.version }}"

      - name: Tag ${{ steps.release_version.outputs.version }}
        run: |
          git tag -a ${{ steps.release_version.outputs.version_tag }} -m "chore(release): ${{ steps.release_version.outputs.version }}"

      - name: Update with the development version
        run: |-
          sed -i -E 's/Version: .*/Version: ${{ steps.release_version.outputs.version }}.9000/g' DESCRIPTION

      - name: Commit with the development version
        run: |
          git add DESCRIPTION
          git commit -m "chore(release): set the development version to ${{ steps.release_version.outputs.version }}.9000"

      - name: Push commits and tags
        run: |
          git push && git push --tags
