name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'New version type [major | minor | patch]'
        required: true
        default: 'patch'
jobs:
  bumpVersion:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "New version type: ${{ github.event.inputs.type }}"

      - name: Branch Protection Bot - Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@1.0.8
        if: always()
        with:
          access_token: ${{ secrets.GH_RELEASE_TOKEN }}
          enforce_admins: false
          branch: main

      - name: Setup checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: Config git
        run: |
          git config --local user.email "62586190+process-analytics-bot@users.noreply.github.com"
          git config --local user.name "process-analytics-bot"
          git config pull.rebase true

      - name: Checkout main
        run: git checkout main && git pull --tags

      - name: Generate new version
        id: release_version
        uses: zwaldowski/semver-release-action@v3
        with:
          dry_run: true
          bump: ${{ inputs.type }}
          prefix: v
          github_token: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: Update with the release version
        run: |
          CURRENT_VERSION=$(grep Version DESCRIPTION | sed 's/Version: \(.*\).9000/\1/g')
          sed -i -E "s/$CURRENT_VERSION/${{ steps.release_version.outputs.version }}/g" index.md
          sed -i -E "s/$CURRENT_VERSION/${{ steps.release_version.outputs.version }}/g" README.md
          sed -i -E "s/$CURRENT_VERSION.9000/${{ steps.release_version.outputs.version }}/g" cran-comments.md
          sed -i -E 's/Version: .*/Version: ${{ steps.release_version.outputs.version }}/g' DESCRIPTION

      - name: Commit with the release version
        run: |
          git add index.md
          git add README.md
          git add cran-comments.md
          git add DESCRIPTION
          git commit -m "chore(release): set the release version to ${{ steps.release_version.outputs.version }}"

      - name: Tag ${{ steps.release_version.outputs.version }}
        run: |
          git tag -a ${{ steps.release_version.outputs.version_tag }} -m "chore(release): ${{ steps.release_version.outputs.version }}"

      - name: Update with the development version
        run: |-
          sed -i -E 's/Version: .*/Version: ${{ steps.release_version.outputs.version }}.9000/g' DESCRIPTION

      - name: Commit with the development version
        run: |
          git add DESCRIPTION
          git commit -m "chore(release): set the development version to ${{ steps.release_version.outputs.version }}.9000"

      - name: Push commits and tags
        run: |
          git push && git push --tags

      - name: Branch Protection Bot - Reenable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@1.0.8
        if: always()  # Force to always run this step to ensure "include administrators" is always turned back on
        with:
          access_token: ${{ secrets.GH_RELEASE_TOKEN }}
          enforce_admins: true
          branch: main
      - name: Send message to Slack channel
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'CSF7TG6N5'
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":mega: bpmnVisualizationR release ${{ steps.release_version.outputs.version_tag }}",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
            	  "accessory": {
                    "type": "image",
                    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/R_logo.svg/1448px-R_logo.svg.png",
                    "alt_text": "Haunted hotel image"
                  },
                  "text": {
                    "type": "mrkdwn",
                    "text": "- <https://github.com/${{github.repository}}/tree/${{ steps.release_version.outputs.version_tag }}|Tag> done :heavy_check_mark:"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "See the next steps <https://github.com/${{github.repository}}/blob/main/MAINTAINERS.md#release-process|here> :arrow_left:"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
